test crud/blog/config/routes.rb
Rails.application.routes.draw do
  get 'android/index'

  get 'posts/index'

    root 'pages#index'
    resources :posts
    get '/android', to: 'android#index'
    get '/android', to: 'android#show'
    get '/android/show', to:'android#show'
    
    resources :posts

end

test crud/blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

test crud/blog/app/models/post.rb
class Post < ApplicationRecord 
    
end

test crud/blog/app/controllers/android_controller.rb
class AndroidController < ApplicationController
  def index
    @android="Hello world"
  end
  def show
    @android="I love Android"
  end
end

test crud/blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

test crud/blog/app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
        
    end
end

test crud/blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    @posts = Post.all
  end
  
  def show
    @posts = Post.find(params[:id])
  end
  
  def edit
    @posts = Post.find(params[:id])
  end
  
  def update
    @posts = Post.find(params[:id])
    @posts.update(params.require(:post).permit(:name, :content))
    redirect_to posts_url ,notice: 'This article has been updated'
  end
  
  def new
    @posts=Post.new
  end
  
  def create
    @posts=Post.create(params.require(:post).permit(:name, :content))
    redirect_to posts_url ,notice: 'This article has been added'
  end
  
  def destroy
    @posts = Post.find(params[:id])
    @posts.destroy
    redirect_to posts_url ,notice: 'This article has been deleted'
  end
end

test crud/blog/app/helpers/android_helper.rb
module AndroidHelper
end

test crud/blog/app/views/android/index.html.erb
 <h1><%= @android %></h1>
 <br>
<a href="android/show"><p>To Android Information</p></a>

test crud/blog/app/views/android/show.html.erb
<h1>Hello</h1>
<h3><%= @android %></h3>

        

test crud/blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title>Blog</title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
    </head>
    <body>
      <%= yield %>
    </body>
</html>

test crud/blog/app/views/pages/index.html.erb
<h1>Salut les gens</h1>

test crud/blog/app/views/posts/_form.html.erb
<%= form_for post do |f| %>
    <%= f.text_field :name %>
    <br>
    <%= f.text_area :content %>
    <br>
    <%= f.submit post.new_record? ? 'Create' : 'Edit' %>
<% end %>

test crud/blog/app/views/posts/edit.html.erb
<h1>Edit Post</h1>
    <br>
    <%= form_for @posts do |f| %>
        <%= f.text_field :name %>
        <br>
        <%= f.text_area :content %>
        <br>
        <%= f.submit 'Edit' %>
    <% end %>
 

test crud/blog/app/views/posts/index.html.erb
<h1>All article</h1>
<% if flash[:notice] %>
    <div class="alert alert-success">
        <%= flash[:notice] %>
    </div>
<% end %>
<ul>
<% @posts.each do |post| %>
    <li><a href="<%= posts_path(id: post.id, name: post.name) %>"><%= post.name %></a></li>
    <li><%= link_to post.name,post %></li> -
    <%= link_to "Edit", [:edit,post] %>-
    <%= link_to 'Delete', post, method: :delete , date: {confirm:'Do you want to delete this article ?'} %>
<% end %>
</ul>
<p><%= posts_path %></p>
<br>
<a href="<%= android_path %>">Android</a>
<br>
<%= link_to 'Create an article', new_post_path %>

test crud/blog/app/views/posts/new.html.erb
<h1>Edit Post</h1>
<br>
<%= render 'form' ,post: @posts %>
    
    

test crud/blog/app/views/posts/show.html.erb
<p><%= link_to 'Return to post pages', Post %></p>
<p><%= link_to 'Android', android_url %></p>
<h1><%= @posts.name %></h1>
<p><%= @posts.content %></p>
<br>
<p><%=  if @posts.created_at==nil
            'Erreur'
        else
            time_ago_in_words(@posts.created_at)
        end
%> </p> 
 